name: '@actalog/dockerfile-ci'
description: CI pipeline for Dockerfile
author: Gabriel Rufino <contato@gabrielrufino.com>
branding:
  icon: refresh-ccw
  color: blue

inputs:
  image-name:
    required: false
    default: image
  image-version:
    required: false
    default: '1.0.0'

runs:
  using: 'composite'
  steps:
    - uses: hadolint/hadolint-action@v3.1.0
    - run: |
        docker image build \
          -t ${{ inputs.image-name }}:latest \
          -t ${{ inputs.image-name }}:${{ inputs.image-version }} \
          .
      shell: bash
    - run: |
        docker image save \
          -o images.tar \
          ${{ inputs.image-name }}:latest
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: dockerfile-ci
        path: |
          images.tar
    - if: ${{ github.event_name == 'pull_request' }}
      id: info
      run: |
        size=$(docker images ${{ inputs.image-name }}:latest --format "{{.Size}}")
        echo "size=$size" >> $GITHUB_OUTPUT
      shell: bash
    - if: ${{ github.event_name == 'pull_request' }}
      uses: peter-evans/create-or-update-comment@v4
      continue-on-error: true
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          # Dockerfile CI

          Dockerfile CI completed!

          ## Statistics

          * **image size:** ${{ steps.info.outputs.size }}
