name: '@actalog/dockerfile-ci'

inputs:
  image-name:
    required: false
    default: image
  image-version:
    required: false
    default: '1.0.0'

runs:
  using: 'composite'
  steps:
    - uses: hadolint/hadolint-action@v3.1.0
    - run: |
        docker image build \
          -t ${{ inputs.image-name }}:latest \
          -t ${{ inputs.image-name }}:${{ inputs.image-version }} \
          .
      shell: bash
    - run: |
        docker image save \
          -o images.tar \
          ${{ inputs.image-name }}:latest
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: dockerfile-ci
        path: |
          images.tar
