name: CI

on:
  - pull_request
  - push
  - workflow_dispatch

permissions:
  pull-requests: write

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: action
          path: action.yml
      - uses: actions/checkout@v4
        with:
          repository: servicespack/proxies-api
      - uses: actions/download-artifact@v4
      - uses: ./action/
        with:
          image-name: servicespack/proxies-api
